// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Models;

public class Article
{
    public int Id { get; set; }

    public string Titre { get; set; }

    public string Contenu { get; set; }

    public string MiniatureUrl { get; set; }

    public int DateTableId { get; set; }

    public string UtilisateurId { get; set; }

    public virtual ICollection<Commentaire>? Commentaires { get; set; } = new List<Commentaire>();

    public virtual DateTable DateNavigation { get; set; }

    public virtual Utilisateur UtilisateurNavigation { get; set; }

    public virtual ICollection<Categorie> Categories { get; set; } = new List<Categorie>();
}