// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models;

public class Categorie
{
    public int Id { get; set; }

    public string Titre { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();
}