// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models;

public class Commentaire
{
    public int Id { get; set; }

    public string Titre { get; set; }

    public string Contenu { get; set; }

    public int DateTableId { get; set; }

    public int ArticleId { get; set; }

    public int UtilisateurId { get; set; }

    public DateTable DateTableNavigation { get; set; }

    public Article ArticleNavigation { get; set; }

    public Utilisateur UtilisateurNavigation { get; set; }
}