// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace Models;

public class Utilisateur
{
    public string Id { get; set; }
    public string Nom { get; set; }
    public string Prenom { get; set; }
    public string Pseudo { get; set; }


    public string AppUserId { get; set; }
    public AppUser AppUser { get; set; }


    public int DateTableId { get; set; }
    public virtual DateTable Dates { get; set; }


    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();
    public virtual ICollection<Commentaire> Commentaires { get; set; } = new List<Commentaire>();

}